# Generated by Django 2.2.2 on 2019-06-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20190625_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='08027164778', max_length=14),
            preserve_default=False,
        ),
    ]
